# -*- coding: utf-8 -*-
"""python_Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZyNM5kugOvVwVv8gY-TbHS8M3CxRVZX
"""

#Q1. Create a Function
def greet():
  print("Hello, Allwin")
  print("Welcome to Python")
greet()

#Q2. Function with a Parameter
def greet(name):
  print ("Hello,", name)
greet("allwin")

#Q3. Add Two Numbers
def add(a,b):
  return a+b
result=add(10,20)
print(result)

#Q4. Square of a Number
def square(n):
  return n**2
a=int(input("Enter a number:"))
print(square(a))

#Q5 — Check Even or Odd
def oddeve(a):
  if a % 2==0:
    print('even')
  else:
    print("odd")
oddeve(int(input("enter a:")))

#Q6 — Find the Largest of Two Numbers
def large(a,b):
  if a> b:
    print( a, " is large")
  else:
    print(b, " is large")
large(int(input("enter a:")),int(input("enter b:")))

#Q7 — Largest of Three Numbers
def large(a,b,c):
  if a > b and a> c:
    print(a, " is large")
  elif b>a and b>c:
    print(b, " is large")
  else:
    print(c, " is large")
large(int(input("enter a:")),int(input("enter b:")),int(input("enter c:")))

#Q8 — Count Vowels
def vowel(a):
  count=0
  for i in a:
    if i in "aeiouAEIOU":
      count+=1
  return count

a=input("enter string: ")
ans=vowel(a)
print(ans)

#Q9 — Sum of a List
def sumlist(numbers):
  sum1=0
  for i in numbers:
    sum1=sum1+i
  return sum1

list1=[10,20,30,40]
eg=sumlist(list1)
print(eg)

#Q10 — Find Largest Number in a List
def lar(numbers):
  largest=numbers[0]
  for i in numbers:
    if i >largest:
      largest=i
  return largest

list1=[34,12,56,7,89,23]
print(lar(list1))

#Q11 — Reverse a String
def rev(string):
  b=""
  for i in range(len(string),0,-1):
    b=b + string[i-1]
  return b
a=input("enter  string: ")

print(rev(a))

#Q12 — Check Palindrome
def pali (string):
  pal=""
  ans="is palindrome"
  for i in range(len(string),0,-1):
    pal=pal+string[i-1]
  if pal == string:
    return ans
  else:
    return string, "is not palindrome"
a=input("enter string: ")
print(pali(a))

#Q13 — Factorial
def fact(n):
  factorial =1
  for i in range(1,n+1):
    factorial=factorial*i
  return factorial
a=int(input("enter number: "))
print(fact(a))

#Q14 — Prime Number
def prime(n):
  if n < 2:
    return "not prime"
  for i in range(2,n):
    if n % i == 0:
      return "not prime"
  return "prime"
a=int(input("enter number: "))
print(prime(a))

#Q15 — Calculator Function
def Calculator(a,b,oper):
  if oper=="+":
    return a+b
  elif oper=="-":
    return a-b
  elif oper=="*":
    return a*b
  elif oper=="/":
    return a/b
  else:
    return "invalid operator"
val=int(input("enter a:"))
val2=int(input("enter b:"))
oper=input("enter operator: ")
print(Calculator(val,val2,oper))

"""# **set 2**"""

#Q1 — Default Parameter
def gre(name="Guest"):
  ans="hello,"+name
  return ans
b=gre("alw")
print(b)

#Q2 — Multiple Parameters
def std_details(name,age,department):
  ans= name +" is " +str(age)+ " years old belongs to "+ department +" department "
  return ans

print(std_details("allwin",20,"cse"))

#Q3 — Return Multiple Values
def cal(a,b):
  sum=a+b
  diff=a-b
  return sum,diff

a=int(input("enter a: "))
b=int(input("enter b: "))
su,di=cal(a,b)
print("Sum =", su)
print("Difference = ",di)

#Q4 — Function with a List
def eve_number(numbers):
  count=0
  for i in numbers:
    if i % 2== 0:
      count+=1

  return count
a = [int(i) for i in input(...).split()]
print(eve_number(a))

#Q5 — Function Calling Another
def square(n):
  return n**2

def sum_of_square(a,b):
  a=square(a)
  b=square(b)
  c=a+b
  return c
a=int(input('enter number:'))
b=int(input('enter number:'))
print(sum_of_square(a,b))

#Q6 — Function with a List: Average
def avg(list1):
  average=0
  for i in list1:
    average+=i
  return average/len(list1)
a=[10,20,30,40,50]
print(avg(a))

#Q7 — Find Both Largest and Smallest
def min_max(list1):
  mini=list1[0]
  maxi=list1[0]
  for i in list1:
    if i > maxi:
      maxi=i
    if i < mini:
      mini=i
  return maxi, mini

numbers = [34, 12, 56, 7, 89, 23]
a,b=min_max(numbers)
print(a,b)

#Q8 — Default Parameter + Calculation
def eg(base,exp=2):
  a=base**exp
  return a

a=int(input("enter base: "))
print(eg(a))

#Q9 — Count Positive, Negative and Zero
def count_num(numbers):
  pos=0
  neg=0
  zero=0
  for i in numbers:
    if i > 0:
      pos+=1
    elif i ==0:
      zero+=1
    else:
      neg+=1
  return pos,neg,zero

a = [10, -5, 0, 20, -3, 0, 7]
x,y,z=count_num(a)
print("positive: ", x)
print("Negative:", y)
print("Zero:", z)

#Q10 — Function with a List + Condition
def hi(n):
  sum=0
  count=0
  avg=0
  for i in n:
    sum=sum+i
    avg=sum/len(n)
  for i in n:
    if i > avg:
      count=count+1
  return sum,avg,count


n=[10, 20, 30, 40, 50]
a,b,c=hi(n)
print("sum:",a)
print("average:",b)
print("count:",c)

#Q11 — Local vs Global Variable
def addall(*numbers):
  add=0
  for i in numbers:
    add=add+i
  return add

print(addall(10, 20, 30, 40))

#Q14 — **kwargs
def std(**details):
  for key,value in details.items():
    print(key,value)
std(name="allwin",age=20)

#Q1 — Second Largest Number
def second_large(numbers):
  large=numbers[0]
  second=numbers[0]
  for i in numbers:
    if i > large:
      large=i
  for i in numbers:
    if i > second and i<large:
      second=i

  return second

numbers = [10, 25, 8, 40, 30]
a=second_large(numbers)
print(a)

#Q2 — Remove Duplicates Without set()
def rem_dup(numbers):
  num2=[]
  for i in numbers:
    if i not in num2:
      count=0
      for j in numbers:
        if i == j:
          count+=1
      num2.append(i)
  return num2



numbers = [10, 20, 10, 30, 20, 40, 30]
a=rem_dup(numbers)
print(a)

#Q3 — Find the Most Frequent Number
def most_fre(numbers):
  ans=0
  num2=[]
  for i in numbers:
    count=0
    if i not in num2:
      for j in numbers:
        if i == j :
          count+=1
      num2.append(i)
      if count > ans:
        ans=count
        freq=i
  return freq

numbers = [10, 20, 10, 30, 20, 10, 40]
print(most_fre(numbers))

#Q4 — One-Pass Second Largest
def sec(numbers):
  large=numbers[0]
  second=0
  for i in numbers:
    if i > large:
      second = large
      large= i
    elif i > second and i != large:
      second = i
  return second

numbers = [10, 25, 8, 40, 30]
print(sec(numbers))

#Q5 — Count Frequency of Each Number
def fre(numbers):
  num2=[]
  result=[]
  for i in numbers:
    if i not in num2:
      count=0
      for j in numbers:
        if i == j:
          count+=1
      num2.append(i)
      result.append((i,count))
  return result


numbers = [10, 20, 10, 30, 20, 10]
a=fre(numbers)
print(a)

#Q6 — Reverse a List Without reverse()
def rev(numbers):
  result=[]
  for i in range(len(numbers)-1,-1,-1):
    result.append(numbers[i])
  return result



numbers = [10, 20, 30, 40, 50]
print(rev(numbers))

#Q7 — Find Missing Number
def mis(numbers):
  for i in range(1,max(numbers)+1):
    if i not in numbers:
      return i


numbers = [1, 2, 3, 5, 6]
print(mis(numbers))

#Q8 — Check Anagram
def anag():

    a = input("Enter first string: ")
    b = input("Enter second string: ")

    if len(a) != len(b):
        return False

    for i in a:
        count_a = 0
        count_b = 0

        for j in a:
            if i == j:
                count_a += 1

        for j in b:
            if i == j:
                count_b += 1

        if count_a != count_b:
            return False

    return True


print(anag())

#Q9 — Find the First Non-Repeating Character
def fnrc():
  a=input("enter string: ")
  ans=""
  for i in a:
    count=0
    for j in a:
      if i == j:
        count+=1
    if count==1:
      ans=ans+i
      break
  return ans

print(fnrc())

#Q10 — Find Common Elements in Two Lists
def com(a,b):
  result=[]
  for i in a:
    if i not in result:
      count=0
      for j in b:
        if j == i:
          count+=1

      if count>0:
        result.append(i)
  return result

a = [10, 20, 30, 40, 50]
b = [30, 40, 60, 70, 10]
print(com(a,b))

#Q11 — Move All Zeros to the End
def mo(numbers):
  result=[]
  for i in numbers:
    if i !=0:
      result.append(i)

  return result + [0] * (len(numbers) - len(result))

numbers = [0, 1, 0, 3, 12]
print(mo(numbers))

#Q12 — Find the Longest Word
def lon(words):
  longest = words[0]
  for i in words:
    if len(i) > len(longest):
      longest=i
  return longest



words = ["apple", "banana", "kiwi", "watermelon"]
print(lon(words))

#Q13 — Count Vowels and Consonants
def cou(words):
  vowels=0
  consonants=0
  for i in words:
    if i in "aeiouAEIOU":
      vowels+=1
    elif i ==" ":
      pass
    else:
      consonants+=1
  return vowels, consonants

words = "hello world"
a,b=cou(words)
print("vowels:",a)
print("consonants:",b)

#Q14 — Find the Largest Difference
def dif(numbers):
  large=numbers[0]
  small=numbers[0]
  for i in numbers:
    if i > large:
      large=i
  for j in numbers:
    if j < small:
      small=j
  return large-small

numbers = [10, 5, 20, 8, 15]
print(dif(numbers))

#Q15 — Check if a List is Palindrome
def pali(numbers):
  for i in range(len(numbers)//2):
    if numbers[i] != numbers[-(i+1)]:
      return False
  return True

numbers = [1, 2, 3, 2, 1]
print(pali(numbers))