# -*- coding: utf-8 -*-
"""python_while_loop,List Comprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gid9_kbCC5Qr4V7jTiQHMQWOBqvWRYrk
"""

#While Q1 — Print Numbers
n=1
while n <=10:
  print(n)
  n+=1

#While Q2 — Print Even Numbers
n=1
while n <=20:
  if n %2==0:
    print(n)
  n+=1

#While Q3 — Sum of Numbers
n=1
Sum=0
while n <=10:
  Sum+=n
  n+=1
print("Sum:", Sum)

#While Q4 — Count Digits
n = 58392
count=0
while n%10:
  count+=1
  n//=10
print("Count:", count)

#While Q5 — Reverse a Number
n = 58392
rev=""
while n>0:
  rev+=(str(n%10))
  n//=10

print(int(rev))

#While Q6 — Sum of Digits
n = 58392
ans=0
while n > 0:
  digit=n%10
  ans=ans+digit
  n//=10
print(ans)

#While Q7 — Count Even and Odd Digits
n = 58392
odd=0
eve=0
while n > 0:
  digi=n%10
  if digi %2==0:
    eve+=1
  else:
    odd+=1
  n//=10
print("Even:", eve)
print("Odd:", odd)

#While Q8 — Find Largest Digit
n = 58392
lar=0
while n > 0:
  digi=n%10
  if digi > lar:
    lar=digi
  n//=10

print(lar)

#While Q9 — Find Smallest Digit
n = 58392
small=100
while n > 0:
  digi=n%10
  if digi < small:
    small=digi
  n//=10

print(small)

#While Q10 — Final Challenge: Palindrome Number
n = 12321
ori=n
rev=0
while n > 0:
  digi=n%10
  rev=rev*10+digi
  n//=10
print(rev)
if ori==rev:
  print("Palindrome")
else:
  print("Not Palindrome")

"""# List Comprehension"""

#Q1 — Create a List of Squares
numbers = [1, 2, 3, 4, 5]
squares = [x**2 for x in numbers]
print(squares)

#List Comprehension Q2 — Find Even Numbers
numbers = [10, 15, 20, 25, 30, 35, 40]
even_numbers = [x for x in numbers if x % 2 == 0]
print(even_numbers)

#List Comprehension Q3 — Odd Numbers
numbers = [10, 15, 20, 25, 30, 35, 40]
odd = [x for x in numbers if x % 2 == 1]
print(odd)

#List Comprehension Q4 — Convert to Uppercase
names = ["allwin", "arun", "bala", "dinesh"]
re= [ i.upper() for i in names]
print(re)

#List Comprehension Q5 — Numbers Greater Than 25
numbers = [10, 20, 30, 40, 50, 15, 35]
re=[i for i in numbers if i > 25]
print(re)

#List Comprehension Q6 — Squares of Even Numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8]
sq=[i**2 for i in numbers if i %2==0]
print(sq)

#List Comprehension Q7 — Convert Positive Numbers
numbers = [-5, 10, -3, 20, -8, 30]
re=[ i for i in numbers if i > 0]
print(re)

#List Comprehension Q8 — Convert Words to Their Lengths
words = ["Python", "Django", "SQL", "PowerBI"]
re=[ len(i) for i in words]
print(re)

#List Comprehension Q9 — Extract Vowels
word = "programming"
re=[i for i in word if i in "aeiouAEIOU"]
print(re)

#List Comprehension Q10 — Final Challenge
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
re=[i**2 for i in numbers if i%2==0 and i>5 ]
print(re)