# -*- coding: utf-8 -*-
"""Python_Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFanT2z3_R8Zx0nu0YRQw2jJ3nwzV9Ke

Python Sets — Set 1

| Operation            | Operator | Method                    |
| -------------------- | -------- | ------------------------- |
| Union                | `\|`     | `.union()`                |
| Intersection         | `&`      | `.intersection()`         |
| Difference           | `-`      | `.difference()`           |
| Symmetric Difference | `^`      | `.symmetric_difference()` |

# Remember
| Operation       | Method          | Operator |
| --------------- | --------------- | -------- |
| Subset          | `.issubset()`   | `<=`     |
| Proper subset   | —               | `<`      |
| Superset        | `.issuperset()` | `>=`     |
| Proper superset | —               | `>`      |
"""

#Q1 — Create a Set and Remove Duplicates
numbers = [10, 20, 10, 30, 20, 40, 30, 50]
numbers2=set(numbers)
print(numbers2)

#Q2 — Add and Remove Elements
numbers = {10, 20, 30, 40}
numbers.add(50)
numbers.remove(20)
print(numbers)

#Q3 — Check Membership
numbers = {10, 20, 30, 40, 50}
if 30 in numbers:
    print("30 is present")

#Q4 — Set Length
numbers = {10, 20, 30, 40, 50, 60, 70}
print(len(numbers))

#Q5 — Find Common Elements
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
print(set1&set2)
print(set1.intersection(set2))

#Q6 — Find All Unique Elements
set1 = {10, 20, 30, 40}
set2 = {30, 40, 50, 60}
print(set1.union(set2))
print(set1|set2)

#Q7 — Find Elements Only in the First Set
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
print(set1-set2)
print(set1.difference(set2))

#Q8 — Find Elements Only in Either Set
set1 = {10, 20, 30, 40}
set2 = {30, 40, 50, 60}
print(set1^set2)
print(set1.symmetric_difference(set2))

#Q9 — Remove Duplicates + Find Common Values
list1 = [10, 20, 20, 30, 40, 40, 50]
list2 = [20, 30, 30, 40, 60, 60]
list1=set(list1)
list2=set(list2)
print(list1)
print(list2)
print(list1&list2)
print(list1.intersection(list2))

#Q10 — Set Subset Check
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40}
print(set2.issubset(set1))
print(set2 <= set1)

"""# Python Sets — Set 2."""

#Q1 — Find Unique Numbers
numbers = [10, 20, 10, 30, 40, 20, 50, 30, 60]
numbers=set(numbers)
print(numbers)
count=0
for i in numbers:
  count+=1
print(count)


print(len(numbers))

#Q2 — Find Common Numbers From 3 Sets
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60}
set3 = {30, 40, 70, 80}

print(set1&set2&set3)
print(set1.intersection(set2,set3))

#Q3 — Remove Common Elements
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

print(set1^set2)
print(set1.symmetric_difference(set2))

#Q4 — Find Missing Elements
all_numbers = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
present_numbers = {2, 4, 6, 8, 10}

print(all_numbers-present_numbers)
print(all_numbers.difference(present_numbers))

#Q5 — Find Duplicate Values Using Sets
numbers = [10, 20, 30, 20, 40, 50, 30, 60, 10]
numbers1=set()
for i in numbers:
  count=0
  for j in numbers:
    if i == j:
      count+=1
  if count > 1:
    numbers1.add(i)

print(numbers1)


#another method
numbers = [10, 20, 30, 20, 40, 50, 30, 60, 10]

duplicates = set()

for i in numbers:
    if numbers.count(i) > 1:
        duplicates.add(i)

print(duplicates)

#Q6 — Find Unique Elements
numbers = [10, 20, 10, 30, 40, 20, 50, 30, 60]
uni=set()
for i in numbers:
  if numbers.count(i)==1:
    uni.add(i)


print(uni)

#Q7 — Check Whether Two Sets Are Disjoint
set1 = {10, 20, 30}
set2 = {40, 50, 60}
print(set1.isdisjoint(set2))

#Q8 — Find Common Students
python_students = {"Allwin", "Arun", "Bala", "Dinesh"}
java_students = {"Bala", "Dinesh", "Karthik", "Rahul"}
ans=set()
for i in python_students:
  if i in java_students:
    print(i)
    ans.add(i)
print(ans)



print(python_students & java_students)

#Q9 — Find Students Who Learn Only One Subject
python_students = {"Allwin", "Arun", "Bala", "Dinesh"}
java_students = {"Bala", "Dinesh", "Karthik", "Rahul"}

print(python_students^java_students)
print(python_students.symmetric_difference(java_students))

#Q10 — Find Duplicate Names
names = ["Allwin", "Arun", "Bala", "Allwin", "Dinesh", "Arun", "Karthik"]
dup=set()
for i in names:
  if names.count(i)> 1:
    dup.add(i)
print(dup)

"""# Python Sets — Set 3."""

#Q1 — Find Elements Greater Than Average
numbers = {10, 20, 30, 40, 50}
total=0
ans=set()
for i in numbers:
  total=total+i
print("Average: ",total/len(numbers))
for i in numbers:
  if i > total/len(numbers):
    ans.add(i)
print("Greater than average: ",ans)

#Q2 — Find Unique Common Elements
set1 = {10, 20, 20, 30, 40, 50}
set2 = {20, 30, 30, 40, 60, 70}
print(set1&set2)

#Q3 — Find Values Present in Exactly Two Sets
set1 = {10, 20, 30, 40}
set2 = {20, 30, 50, 60}
set3 = {30, 40, 70, 80}
uni=set1|set2|set3
ans=set()
for i in uni:
  count=0
  if i in set1:
    count+=1
  if i in set2:
    count+=1
  if i in set3:
    count+=1
  if count == 2:
    ans.add(i)
print(ans)
print(uni)

#Q4 — Find Elements in All Sets
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60}
set3 = {20, 30, 70}
ans=set1&set2&set3
print(ans)

#Q5 — Find Numbers Present in Only One Set
set1 = {10, 20, 30, 40}
set2 = {20, 30, 50, 60}
set3 = {30, 40, 70, 80}
uni=set1|set2|set3
ans=set()
for i in uni:
  count=0
  if i in set1:
    count+=1
  if i in set2:
    count+=1
  if i in set3:
    count+=1
  if count == 1:
    ans.add(i)

print(ans)

#Q6 — Separate Even and Odd Numbers
numbers = {10, 15, 20, 25, 30, 35, 40, 45}
odd=set()
eve=set()
for i in numbers:
  if i % 2==0:
    eve.add(i)
  else:
    odd.add(i)
print(odd)
print(eve)

#Q7 — Find Missing Numbers
numbers = {1, 2, 3, 5, 6, 8, 10}
ans=set()
for i in range(1,11):
  if i not in numbers:
    ans.add(i)
print(ans)

#Q8 — Find the Largest and Smallest Values
numbers = {45, 12, 78, 23, 9, 56, 34}
large = next(iter(numbers))
small = next(iter(numbers))
for i in numbers:
  for j in numbers:
    if i > j :
      large=i
    if i <small:
      small=i

print("Largest: ",large)
print("smallest: ",small)

#Q9 — Common but Not in Third Set
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60, 70}
set3 = {30, 40, 80, 90}

a=set1&set2
print(a-set3)

#Q10 — Final Challenge
'''
Find numbers that satisfy both conditions:

Present in at least two sets
NOT present in all three sets
'''

set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60, 70}
set3 = {30, 40, 70, 80, 90}

tot=set1|set2|set3
ans=set()
for i in tot:
  count=0
  if i in set1:
    count+=1
  if i in set2:
    count+=1
  if i in set3:
    count+=1
  if count == 2:
    ans.add(i)

print(ans)

"""# Python Sets — Set 4"""

#Q1 — Find Duplicate Numbers from User Input

n=list(map(int,input("enter the number: ").split()))
n1=set(n)
dup=set()
for i in n1:
  count=0
  for j in n:
    if i == j:
      count+=1
  if count > 1:
    dup.add(i)
print(dup)

#Q2 — Two Sets from User Input
a=set(map(int,input("enter the number: ").split()))
b=set(map(int,input("enter the number: ").split()))
print(a&b)
print(a - b)
print(b - a)

#Q3 — Find Duplicate Numbers Without count()
numbers = [10, 20, 30, 20, 40, 50, 30, 60, 10]
set1=set()
dup=set()
for i in numbers:
  if i not in set1:
    set1.add(i)
  else:
    dup.add(i)
print(dup)

#Q4 — Find Unique Numbers Without count()
numbers = [10, 20, 10, 30, 40, 20, 50, 30, 60]
set1=set()
dup=set()
for i in numbers:
  if i not in set1:
    set1.add(i)
  else:
    dup.add(i)
print(set1-dup)

#Q5 — Find Common Elements Without &
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60, 70}
com=set()
for i in set1:
  if i in set2:
    com.add(i)
print(com)

#Q6 — Find Difference Without -
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60, 70}
dif=set()
for i in set1:
  if i not in set2:
    dif.add(i)
print(dif)

#Q7 — Find Common Elements from 3 Sets Without Set Operations
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60}
set3 = {20, 30, 70}
com=set()
for i in set3:
  if i in set1 and i in set2:
    com.add(i)
print(com)

#Q8 — Find Elements Present in Exactly Two Sets
set1 = {10, 20, 30, 40}
set2 = {20, 30, 50, 60}
set3 = {30, 40, 70, 80}
com=set1|set2|set3
ans=set()
for i in com:
  count=0
  if i in set1:
    count+=1
  if i in set2:
    count+=1
  if i in set3:
    count+=1
  if count == 2:
    ans.add(i)
print(ans)

#Q9 — Find Elements Present in Exactly One Set
set1 = {10, 20, 30, 40}
set2 = {20, 30, 50, 60}
set3 = {30, 40, 70, 80}
com=set1|set2|set3
ans=set()
for i in com:
  count=0
  if i in set1:
    count+=1
  if i in set2:
    count+=1
  if i in set3:
    count+=1
  if count == 1:
    ans.add(i)
print(ans)

#Q10 — Final Challenge
'''
Conditions
Present in at least two sets
NOT present in all three sets
'''
set1 = {10, 20, 30, 40, 50}
set2 = {20, 30, 40, 60, 70}
set3 = {30, 40, 70, 80, 90}

com=set1|set2|set3
ans=set()
for i in com:
  count=0
  if i in set1:
    count+=1
  if i in set2:
    count+=1
  if i in set3:
    count+=1
  if count == 2:
    ans.add(i)
print(ans)

"""Sets — Set 5."""

#Q1 — Remove Duplicates While Preserving Order
numbers = [10, 20, 10, 30, 20, 40, 30, 50]
seen = set()
result = []
for i in numbers:
  if i not in seen:
    seen.add(i)
    result.append(i)

print(seen)
print(result)

#Q2 — Find the First Duplicate
numbers = [10, 20, 30, 40, 20, 50, 30]
set1=set()
for i in numbers:
  if i not in set1:
    set1.add(i)
  else:
    print("First duplicate: ",i)
    break

#Q3 — Find Elements That Appear in Both Lists
list1 = [10, 20, 30, 40, 50]
list2 = [30, 40, 50, 60, 70]
tot=set(list1)|set(list2)
ans=set()
for i in tot:
  if i in list1 and i in list2:
    ans.add(i)
print(ans)

#Q4 — Find Elements in List 1 but Not List 2
list1 = [10, 20, 30, 40, 50]
list2 = [20, 40, 60, 70]
set1=set(list1)
ans=set()
for i in set1:
  if i not in list2:
    ans.add(i)
print(ans)

#Q5 — Find Common Unique Names
names1 = ["Allwin", "Arun", "Bala", "Allwin", "Dinesh"]
names2 = ["Bala", "Dinesh", "Karthik", "Bala", "Rahul"]
set1=set(names1)
ans=set()
for i in set1:
  if i in names2:
    ans.add(i)
print(ans)

#Q6 — Find Names Present in Only One List
names1 = ["Allwin", "Arun", "Bala", "Dinesh"]
names2 = ["Bala", "Dinesh", "Karthik", "Rahul"]
set1=set(names1)
set2=set(names2)
ans=set()
for i in set1:
  if i not in names2:
    ans.add(i)
for i in set2:
  if i not in names1:
    ans.add(i)
print(ans)

#Q7 — Find the Most Frequent Number Without count()
numbers = [10, 20, 10, 30, 20, 10, 40, 20, 20]

frequency = {}

for i in numbers:
    if i in frequency:
        frequency[i] += 1
    else:
        frequency[i] = 1

print(frequency)

max_frequency = max(frequency.values())

for i in frequency:
    if frequency[i] == max_frequency:
        print("Most frequent:", i)
        print("Frequency:", frequency[i])

#Q8 — Common Numbers from 3 Lists
list1 = [10, 20, 30, 40, 50]
list2 = [20, 30, 40, 60, 70]
list3 = [30, 40, 80, 90]
a = set(list1)
ans = set()
for i in list2:
    if i in a and i in list3:
        ans.add(i)
print(ans)

# Q9 — Unique Elements Across Two Lists

list1 = [10, 20, 20, 30, 40]
list2 = [20, 30, 50, 60, 60]

frequency = {}

for i in list1 + list2:
    if i in frequency:
        frequency[i] += 1
    else:
        frequency[i] = 1

ans = set()

for i in frequency:
    if frequency[i] == 1:
        ans.add(i)

print(ans)

#Q10 — Final Challenge
#Find numbers that appear in exactly two lists.
list1 = [10, 20, 30, 40, 50]
list2 = [20, 30, 60, 70]
list3 = [30, 40, 70, 80]
que=set(list1)|set(list2)|set(list3)
ans=set()
for i in que:
  count=0
  if i in list1:
    count+=1
  if i in list2:
    count+=1
  if i in list3:
    count+=1
  if count==2:
    ans.add(i)

print(ans)